### ISSUE TITLE
Implement new methods possible?

### ISSUE THREAD

**Issue by TorstenVeit** [KevinXu02/nerfstudio-webui#2]
I tested the gui and like it. Is it planned to implement methods like splatfacto-big or nerfacto-huge?

**Comment by KevinXu02** [comment]
Hi! The gui automatically reads from nerfstudio configs. But it need the method has a description in the beginning of the configs/method_configs.py. So you might need to add these two methods’ name manually in that file.
I’m planning to make a pr adding these descriptions.
